name: Build application

on: [push, pull_request]

jobs:
  ubuntu-gcc-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install g++-9
        sudo apt-get install cppcheck
        sudo apt-get install libtbb-dev
        sudo apt-get install python3-pip
        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install setuptools cpplint
        sudo apt-get install valgrind
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -D USE_SEQ=ON -D USE_TBB=ON -D USE_STD=ON -D CMAKE_BUILD_TYPE=RELEASE ..
        make -j4
        cd ..
      env:
        CC: gcc-9
        CXX: g++-9
    - name: Run tests
      run: |
        source scripts/run.sh
  ubuntu-clang-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install cppcheck
        sudo apt-get install clang-8 libtbb-dev
        sudo apt-get install python3-pip
        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install setuptools cpplint
        sudo apt-get install valgrind
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -D USE_SEQ=ON -D USE_TBB=ON -D USE_STD=ON -D CMAKE_BUILD_TYPE=RELEASE ..
        make -j4
        cd ..
      env:
        CC: clang-8
        CXX: clang++-8
    - name: Run tests
      run: |
        source scripts/run.sh
  windows-msvc-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Build
      run: |
        mkdir build
        cd build && cmake -D USE_SEQ=ON -D USE_TBB=ON -D USE_STD=ON .. -A Win32
        cmake --build .
      shell: cmd
    - name: Run tests
      run: |
        scripts/run.bat
